@extends('layout')
@section('title','Moj plan izleta')
@section('content')
<div class="page-heading"><div><span class="eyebrow">SPREMLJENO ZA KASNIJE</span><h1>Moj plan izleta</h1><p>Odaberi datume, uskladi društvo i kreni svojim tempom.</p></div>@if($items->count())<a class="btn btn-outline" href="{{ route('trip.print') }}">Pripremi za ispis ↗</a>@endif</div>
<div class="detail-grid"><section>
@forelse($items as $item)<article class="panel trip-card"><img src="{{ \App\Support\Media::url($item->offer->image) }}" alt="{{ $item->offer->title }}"><div><span class="location">{{ $item->offer->city->name }} · {{ $item->offer->duration }} h</span><h2>{{ $item->offer->title }}</h2><p class="small muted">{{ number_format($item->offer->price,2,',','.') }} KM po osobi</p>
@if(!$item->offer->active)<div class="notice error">Ponuda više nije aktivna i nije uključena u ukupan iznos.</div>@endif
<form method="post" action="{{ route('trip.update',$item) }}">@csrf @method('PUT')<div class="trip-fields"><div><label for="date-{{ $item->id }}">Datum posjeta</label><input type="date" class="date-picker" id="date-{{ $item->id }}" name="visit_date" min="{{ date('Y-m-d') }}" value="{{ $item->visit_date }}"></div><div><label for="persons-{{ $item->id }}">Osobe</label><input type="number" id="persons-{{ $item->id }}" name="persons" min="1" max="20" required value="{{ $item->persons }}"></div><div><label for="note-{{ $item->id }}">Napomena</label><input id="note-{{ $item->id }}" name="note" required maxlength="500" value="{{ $item->note }}" placeholder="Npr. polazak u 9 sati"></div></div><div class="trip-footer"><strong>{{ number_format($item->offer->price * $item->persons,2,',','.') }} KM</strong><button class="btn btn-small">Spremi izmjene</button></div></form>
<form method="post" action="{{ route('trip.destroy',$item) }}" data-confirm="Ukloniti ponudu iz vašeg plana?" style="margin-top:16px">@csrf @method('DELETE')<button class="text-link danger-link">Ukloni iz plana</button></form></div></article>
@empty<div class="empty-state"><h2>Tvoj plan još čeka prvi izlet.</h2><p>U katalogu otvori ponudu i odaberi „Dodaj u moj plan”.</p><a class="btn" href="{{ route('catalog') }}">Istraži ponudu →</a></div>@endforelse
</section><aside><div class="panel"><span class="eyebrow">PREGLED PLANA</span><h3>{{ $items->count() }} spremljenih ponuda</h3><strong class="price-large">{{ number_format($total,2,',','.') }} KM</strong><p class="muted">Procijenjeni trošak za odabrani broj osoba.</p><p class="small muted">Iznos se ažurira nakon spremanja izmjena. Prijevoz i dodatni troškovi nisu uključeni. Ovo nije rezervacija.</p><a class="btn btn-outline full" href="{{ route('catalog') }}">Dodaj još doživljaja</a></div></aside></div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('vendor/flatpickr.css') }}">@endpush
@push('scripts')<script src="{{ asset('vendor/flatpickr.js') }}"></script><script>if(window.flatpickr) flatpickr('.date-picker',{dateFormat:'Y-m-d',minDate:'today',allowInput:true,disableMobile:true});</script>@endpush
