@extends('layout')
@section('title','Gradovi i kategorije')
@section('content')
<div class="page-heading"><div><span class="eyebrow">ADMINISTRACIJA</span><h1>Gradovi i kategorije</h1><p>Grad ili kategorija mogu se obrisati kada nemaju povezanih ponuda.</p></div></div>@include('admin.nav')
<div class="detail-grid"><div><section class="panel"><h2>Gradovi</h2><div class="table-wrap"><table><thead><tr><th>Naziv</th><th>Ponude</th><th>Radnje</th></tr></thead><tbody>@foreach($cities as $city)<tr><td>{{ $city->name }}</td><td>{{ $city->offers_count }}</td><td><div class="actions"><a class="text-link" href="{{ route('admin.lists',['city'=>$city->id]) }}#city-form">Uredi</a><form method="post" action="{{ route('admin.cities.destroy',$city) }}" data-confirm="Obrisati grad?">@csrf @method('DELETE')<button class="text-link danger-link">Obriši</button></form></div></td></tr>@endforeach</tbody></table></div></section>
<form class="panel" id="city-form" method="post" action="{{ $editCity ? route('admin.cities.update',$editCity) : route('admin.cities.store') }}">@csrf @if($editCity) @method('PUT') @endif<h2>{{ $editCity ? 'Uredi grad' : 'Dodaj grad' }}</h2>
<label for="city-name">Naziv grada</label><input id="city-name" name="name" maxlength="80" required value="{{ old('name',$editCity?->name) }}"><label for="city-description">Kratki opis</label><textarea id="city-description" name="description" required minlength="10" maxlength="2000">{{ old('description',$editCity?->description) }}</textarea>
<div class="split-fields"><div><label for="latitude">Geografska širina</label><input id="latitude" name="latitude" type="number" min="-90" max="90" step="0.000001" required value="{{ old('latitude',$editCity?->latitude) }}"></div><div><label for="longitude">Geografska dužina</label><input id="longitude" name="longitude" type="number" min="-180" max="180" step="0.000001" required value="{{ old('longitude',$editCity?->longitude) }}"></div></div><p class="field-help">Koordinate služe za vremensku prognozu i poveznicu na kartu.</p><div class="actions" style="margin-top:20px"><button class="btn">Spremi grad</button>@if($editCity)<a href="{{ route('admin.lists') }}">Odustani</a>@endif</div></form></div>
<div><section class="panel"><h2>Kategorije</h2>@foreach($categories as $category)<div class="review"><strong>{{ $category->name }}</strong><p class="small muted">{{ $category->offers_count }} ponuda</p><div class="actions"><a class="text-link" href="{{ route('admin.lists',['category'=>$category->id]) }}#category-form">Uredi</a><form method="post" action="{{ route('admin.categories.destroy',$category) }}" data-confirm="Obrisati kategoriju?">@csrf @method('DELETE')<button class="text-link danger-link">Obriši</button></form></div></div>@endforeach</section>
<form class="panel" id="category-form" method="post" action="{{ $editCategory ? route('admin.categories.update',$editCategory) : route('admin.categories.store') }}">@csrf @if($editCategory) @method('PUT') @endif<h3>{{ $editCategory ? 'Uredi kategoriju' : 'Dodaj kategoriju' }}</h3><label for="category-name">Naziv kategorije</label><input id="category-name" name="name" required maxlength="80" value="{{ old('name',$editCategory?->name) }}"><button class="btn full">Spremi kategoriju</button>@if($editCategory)<a href="{{ route('admin.lists') }}">Odustani</a>@endif</form></div></div>
@endsection
