@extends('layout')
@section('title',$offer->exists ? 'Uredi ponudu' : 'Nova ponuda')
@section('content')
<div class="page-heading"><div><span class="eyebrow">ADMINISTRACIJA / PONUDE</span><h1>{{ $offer->exists ? 'Uredi ponudu' : 'Nova ponuda' }}</h1></div><a href="{{ route('admin.index') }}">← Natrag na ponude</a></div>
<form method="post" enctype="multipart/form-data" action="{{ $offer->exists ? route('admin.offers.update',$offer) : route('admin.offers.store') }}" class="panel edit-form" id="offer-form">@csrf @if($offer->exists) @method('PUT') @endif
<label for="title">Naziv ponude</label><input id="title" name="title" required minlength="3" maxlength="150" value="{{ old('title',$offer->title) }}">
<div class="split-fields"><div><label for="city_id">Grad</label><select id="city_id" name="city_id" required>@foreach($cities as $city)<option value="{{ $city->id }}" @selected(old('city_id',$offer->city_id)==$city->id)>{{ $city->name }}</option>@endforeach</select></div><div><label for="category_id">Kategorija</label><select id="category_id" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$offer->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div></div>
<label for="description">Opis ponude</label><textarea id="description" name="description" required maxlength="15000">{{ old('description',$offer->description) }}</textarea><div id="editor" hidden></div>
<div class="split-fields"><div><label for="price">Cijena po osobi (KM)</label><input id="price" name="price" type="number" min="0" max="99999" step="0.01" required value="{{ old('price',$offer->price ?? 0) }}"></div><div><label for="duration">Trajanje (sati)</label><input id="duration" name="duration" type="number" min="1" max="168" required value="{{ old('duration',$offer->duration ?? 2) }}"></div></div>
<div class="split-fields"><div><label for="image">Fotografija</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp"><p class="field-help">JPG, PNG ili WebP do 4 MB, najviše 6000 × 6000 px. Prazno polje zadržava postojeću fotografiju.</p>@if($offer->image)<img src="{{ \App\Support\Media::url($offer->image) }}" alt="Trenutačna fotografija" style="height:100px;border-radius:8px">@endif</div><div><label for="brochure">PDF brošura</label><input id="brochure" name="brochure" type="file" accept="application/pdf"><p class="field-help">PDF do 5 MB. Prazno polje zadržava postojeću brošuru.</p>@if($offer->brochure)<a class="text-link" href="{{ \App\Support\Media::url($offer->brochure) }}">Trenutačna brošura</a>@endif</div></div>
<label class="check-label"><input type="checkbox" name="active" value="1" @checked(old('active',$offer->exists ? $offer->active : true))> Ponuda je aktivna i vidljiva posjetiteljima</label>
<div class="actions" style="margin-top:24px"><button class="btn">Spremi ponudu</button><a href="{{ route('admin.index') }}">Odustani</a></div></form>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('vendor/quill.css') }}">@endpush
@push('scripts')<script src="{{ asset('vendor/quill.js') }}"></script><script src="{{ asset('js/editor.js') }}"></script>@endpush
