@extends('layout')
@section('title','Korisnici i uloge')
@section('content')
<div class="page-heading"><div><span class="eyebrow">SUPERADMINISTRATOR</span><h1>Korisnici i uloge</h1><p>Deaktivacija čuva spremljene podatke, a korisniku ukida pristup.</p></div></div>@include('admin.nav')
<section class="panel"><form method="get" class="actions"><label for="user-search">Pretraži korisnike</label><input id="user-search" name="q" value="{{ request('q') }}" maxlength="100" placeholder="Ime, korisničko ime ili email" style="max-width:420px"><button class="btn btn-small">Traži</button><a href="{{ route('admin.users') }}">Poništi</a></form>
<div class="table-wrap" style="margin-top:20px"><table><thead><tr><th>Korisnik</th><th>Email</th><th>Uloga</th><th>Status</th><th>Radnje</th></tr></thead><tbody>@forelse($users as $user)<tr><td>{{ $user->name }}<small>{{ $user->username }}</small></td><td>{{ $user->email }}</td><td>{{ $user->role }}</td><td>{{ $user->active ? 'Aktivan' : 'Neaktivan' }}</td><td><div class="actions"><a class="text-link" href="{{ route('admin.users',['edit'=>$user->id]) }}#user-form">Uredi</a>@if($user->active && $user->id !== auth()->id())<form method="post" action="{{ route('admin.users.destroy',$user) }}" data-confirm="Deaktivirati korisnika?">@csrf @method('DELETE')<button class="text-link danger-link">Deaktiviraj</button></form>@endif</div></td></tr>@empty<tr><td colspan="5">Nema korisnika za upisani pojam.</td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['page'=>$users])</section>
<div class="detail-grid"><form class="panel" id="user-form" method="post" action="{{ $editUser ? route('admin.users.update',$editUser) : route('admin.users.store') }}">@csrf @if($editUser) @method('PUT') @endif<h2>{{ $editUser ? 'Uredi korisnika' : 'Dodaj korisnika' }}</h2>
<div class="split-fields"><div><label for="name">Ime i prezime</label><input id="name" name="name" required minlength="2" maxlength="80" value="{{ old('name',$editUser?->name) }}"></div><div><label for="username">Korisničko ime</label><input id="username" name="username" required minlength="3" maxlength="40" value="{{ old('username',$editUser?->username) }}"></div></div>
<label for="email">Email</label><input id="email" name="email" type="email" required maxlength="150" value="{{ old('email',$editUser?->email) }}"><label for="password">{{ $editUser ? 'Nova lozinka (prazno zadržava staru)' : 'Lozinka' }}</label><input id="password" name="password" type="password" minlength="8" maxlength="72" autocomplete="new-password" @required(!$editUser)>
<label for="role">Uloga</label><select id="role" name="role">@foreach(['korisnik'=>'Korisnik','admin'=>'Administrator','superadmin'=>'Superadministrator'] as $value=>$label)<option value="{{ $value }}" @selected(old('role',$editUser?->role)==$value)>{{ $label }}</option>@endforeach</select>
<label class="check-label"><input name="active" value="1" type="checkbox" @checked(old('active',$editUser ? $editUser->active : true))> Račun je aktivan</label><div class="actions" style="margin-top:20px"><button class="btn">Spremi korisnika</button>@if($editUser)<a href="{{ route('admin.users') }}">Odustani</a>@endif</div></form>
<aside class="panel"><h2>Dozvole uloga</h2><p class="small muted">Pregled ovlasti spremljenih u bazi.</p>@foreach($roles as $role)<div class="review"><h3>{{ $role->name }}</h3><ul>@foreach($role->permissions as $permission)<li class="small">{{ $permission->description }}</li>@endforeach</ul></div>@endforeach<p class="field-help">Superadministrator jedini dodjeljuje uloge. Vlastiti pristup nije moguće ukloniti kroz ovu formu.</p></aside></div>
@endsection
